### ISSUE TITLE
Inject custom configuration per section

### ISSUE THREAD

**Issue by DaveOHenry** [haproxytech/kubernetes-ingress#110]
Is there a way to directly inject lines into the configuration per section (global, defaults, frontend, backend, listen, peers, resolvers and mailers)? Basically I'd just like to add some of my existing rules / configuration into different sections, but it looks like it's not possible. I'd like to add some lines like:
- http-request redirect ... 
- http-request deny ... 
- http-request set-header ...
- http-request set-path ...
- http-response redirect ...
- http-response del-header ...
- http-response set-header ...
- stick-table ...
- stick on path,regsub ...
- http-request track-sc1 ...
- http-request tarpit ...
- http-request set-method ...
- http-request silent-drop ...
- tcp-request content track-sc0 src ...

Sometimes the rules are paired with conditions like: 
... if { var(txn.path) -m something }
... if { something1 } or { something2 } { something3 }

**Comment by oktalz** [comment]
Hi @DaveOHenry 
yes, currently something like this is not possible to do.

there is and option to add it in file and build image yourself,
however, something like that has some limitations.
If you add it manually in global and defaults sections they will stay
(parts that are not configurable through annotations or configmap),

for frontend, http-request rules are overwritten, other types should stay intact.
for backends, hm, I'm not really sure what would happen if they are predefined.

Could you explain what is a usage/purpose for something like that, 
since ingress controller is mostly configured through configmap 
and ingress (and other k8s) objects

**Comment by DaveOHenry** [comment]
I am currently researching how to move our infrastructure to kubernetes and thought that a kubernetes-ingress could replace our existing loadbalancers where we use many of the features that haproxy provides. 

Unfortunately all of our services need some tweaking either in the request or the response phase which works great with our current haproxy instances, but has some limitations regarding scalability, dynamic configuration and so on. I thought that it should be possible to just split our existing configuration into parts for each application and add the appropriate lines to the ingress definitions somehow.

**Comment by vinayus** [comment]
This would be a very useful feature for us.

**Comment by ailenli** [comment]
maybe can use ingress.annotation like **frontend.snippet backend.snippet** for custom configuration

**Comment by Mo3m3n** [comment]
This is available in 1.5 with [config-snippet](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#config-snippet) annotations
