### ISSUE TITLE
CreateContainerConfigError at deployment

### ISSUE THREAD

**Issue by devdattakulkarni** [haproxytech/kubernetes-ingress#127]
I am trying to deploy haproxy-ingress.yaml and running into 'CreateContainerConfigError' for both the Pods (ingress-default-backend and haproxy-ingress). The detailed error message for both is as follows:

Error: container has runAsNonRoot and image will run as root.

My environment:

- minikube-0.35.0
- Kubernetes 
  - Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Mo3m3n** [comment]
Hi
Which yaml file are you using to deploy the controller?
I am asking because the one in our doc https://github.com/haproxytech/kubernetes-ingress/blob/master/deploy/haproxy-ingress.yaml does not have runAsNonRoot directive.
Also you can try deploying the controller using our Helm Chart: https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress
