### ISSUE TITLE
Bad logging statement?

### ISSUE THREAD

**Issue by whyvez** [haproxytech/kubernetes-ingress#156]
I am troubleshooting an issue and getting this logged out:

`2020/02/20 23:39:13 controller.go:413: Targetport '' not found for service api-accounts`

Looking at the function there doesn't seem to have any reference to ` sp.TargetPortStr` except this logging statement.

https://github.com/haproxytech/kubernetes-ingress/blob/8fed7bcfac70ee112d7c77e8545cb8bdc897b352/controller.go#L392-L419

Could this be a typo and should be `path.TargetPort`?

```diff
- log.Printf("Targetport '%s' not found for service %s", sp.TargetPortStr, service.Name)
+ log.Printf("Targetport '%s' not found for service %s", path.TargetPort, service.Name)
```

**Comment by Mo3m3n** [comment]
Thanks for reporting this, this brought my attention to the fact that we don't need to store the targetPort of a service since the controller directly fetches the port from endpoints.
However this should not be `path.TargetPort` but rather `sp.Name` (the purpose of that function is to actually set path.TargetPort from endpoints)
 You can see in the [commit](https://github.com/haproxytech/kubernetes-ingress/commit/1d36d540fd48600cf92428e7f3a9d6346e791c4d) that the message is now `Could not find Targetport of '%s' for service %s", sp.Name, service.Name`
You can try the `haproxytech/kubernetes-ingress:dev` image and let us know if you have a more coherent message.

**Comment by whyvez** [comment]
@Mo3m3n Ok perfect. I've gotten The NGINX and AWS ALB ingress working but for some reason, the HAProxy isn't working, just getting 404s. Based on this error, any chance you would know what could be going on?

**Comment by Mo3m3n** [comment]
getting 404 probably means that you're getting answer from default backend and that your request did not much any ingress rules.
So  first step would be to look to the controller's logs and see if there is anything abnormal and then have a look to /etc/haproxy/haproxy.cfg inside the controller's pod.
For more help you can find us in [slack](slack.haproxy.com) at the #ingress-controller channel
