### ISSUE TITLE
Kubernetes TLS secret update not working when launched with --default-ssl-certificate=namespace/certsecret

### ISSUE THREAD

**Issue by splicemaahs** [haproxytech/kubernetes-ingress#164]
https://github.com/haproxytech/kubernetes-ingress/blob/361332db168322571c9353efc481e9799e1a8355/controller/https.go#L143

When I launch with 
`      
  containers:
      - args:
        - --default-ssl-certificate=namespace/certname
`

And then update the certificate nothing happens.   However if I comment out the IF block linked above it works fine.  

If someone who understands the use case for this block, that is all I'm looking for.  Everything is working in my currently very narrow use of haproxy with this block commented out.

Thanks for the great work.

**Comment by Mo3m3n** [comment]
Hi @splicemaahs 
First sorry for the long delay getting back to this, we've been quite busy and the suggested fix (removing whole ` if secretAnn.Status == DELETED || secretAnn.Status == EMPTY { ` is not ideal.
This was fixed in `v.1.4.3` more precisely in commit  https://github.com/haproxytech/kubernetes-ingress/commit/b2687c7e0f4a064b73ce72fcc3d5db4b72646309
