### ISSUE TITLE
SyncPeriod default value not honored

### ISSUE THREAD

**Issue by inge4pres** [haproxytech/kubernetes-ingress#197]
Hi there,

on version 1.4.4 we noticed a problem when running the controller without any cmd line args.
`SyncPeriod` default value does not seem to be working, there is an indeterminate period of time waiting for the monitoring loop to start refreshing.
The default value is defined in the `utils.OSArgs` meta-tags but apparently is not parsed correctly...
I send a PR with some tests and my findings.

**Comment by oktalz** [comment]
hi @inge4pres 
it is working correctly and it is set in main at start correctly.

however i suspect this might be an issue because of  missing `--ingress.class`
we had a bug/inconsistency that caused controller to use ingress objects that 
had this set even though this was not set in haproxy.

since controller does not see any ingress objects as his, no change is done, 
and that would also mean that no log messages will appear because 
reload is not needed.

**Comment by oktalz** [comment]
i will soon issue a 1.4.5 that has one major bug (already in master) 
that also might be the reason for this behavior

**Comment by inge4pres** [comment]
Hi @oktalz thanks for the prompt reply!
Indeed in our setup we are leveraging the default "" ingress class...
What is this bug you are mentioning?
I'd still like to point out that the test I wrote in the PR https://github.com/haproxytech/kubernetes-ingress/pull/198/files#diff-bff320ef6eea1bdf5e709ccff6db075cR11 does not pass without the addition in `defaultAnnotations`.
Generally adding some tests to the project could be worth it.

**Comment by inge4pres** [comment]
Also regarding setting the default in `main.go`, not sure how the `long` struct tag is parsed but SyncPeriod` is defaulting to `5s`. I don't thin that is a valid `time.Duration` value, but a `time.Duration.String()`, anyway it would be great to validate it with a test

**Comment by oktalz** [comment]
the bug i mentioned was
https://github.com/haproxytech/kubernetes-ingress/commit/7553b7658ca6df566e59dfca10b342125088a182

basically, controller did not warn about possible miss-configurations in certain cases 
(wrong data in anotation ...)
if you have everything setup-ed correctly there were no issues.

you can expect in about half an hour a new version (and some time to docker-hub builds it).

the test does not pass because it does not reflect actual actions. 
as you see in main.go
``` go
var osArgs utils.OSArgs
var parser = flags.NewParser(&osArgs, flags.IgnoreUnknown)
_, err := parser.Parse()
```
that is how `github.com/jessevdk/go-flags` works

you can't just do 
``` go
osArgs: utils.OSArgs{
     SyncPeriod: 4 * time.Second,
}
```
in order to use `default:"5s"` mentioned in comment of os.args, you need to call Parse.
this is converted back to string, because all annotations are string 
and on init with https://github.com/haproxytech/kubernetes-ingress/blob/master/controller/monitor.go#L21 you get the correct stat

reason why this is done this way is consistency with other parts of code, 
and since this is only done once, that really isn't an issue.

tests are of course welcome and this one is almost perfect.
with minor changes we can add it.

one of the reason why this was not put in `defaultAnnotationValues` is, 
we don't want to have default value in two places, both there and in osargs,
so we just copy it there. At one point we may consider having this more dynamic,
currently this is static, set once on start.

**Comment by inge4pres** [comment]
One other issue I see in the current implementation is the error discard on duration parsing, you could also panic as did in the previous line

**Comment by oktalz** [comment]
@inge4pres,

This is not an issue :)
Please see how github.com/jessevdk/go-flags works.
If you put invalid period, controller will refuse to start and notify you about it.

**Comment by inge4pres** [comment]
Hi @oktalz I'm ok to close this issue once we successfully test v1.4.5 without the cli flag `--sync-period` and see it's working as expected

**Comment by inge4pres** [comment]
Closing as it was fixed upgrading
