### ISSUE TITLE
rate-limit based on a HTTP header

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#211]
Current rate-limit applies to `src` sample fetch. When the ingress Controller sits behind a CDN or an other proxy that don't support proxy-protocol, we want to apply rate limiting on an IP address found in a HTTP header such as `X-Forwarded-For` or `X-Client-IP`

The idea is to have an annotation to provide the name of a header we want to apply rate limiting on

**Comment by Mo3m3n** [comment]
This should be possible starting from `haproxytech/kubernetes-ingress:1.5.0` 
Via [src-ip-header](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#src-ip-header) where haproxy can fetch IP from a HTTP header in request rather than from Layer 4 src ip. And this IP willy apply for all subsequent rules including rate limiting.
