### ISSUE TITLE
path-rewrite Applied in Backends Affecting Multiple Ingresses

### ISSUE THREAD

**Issue by lseelenbinder** [haproxytech/kubernetes-ingress#238]
Currently, `path-rewrite` is applied on a _backend_, which means if multiple ingresses point to the same backend for different entrypoints and only one has a rewrite annotation, the rewrite annotation is applied as if it were on *all* backends. This creates so pretty unexpected behavior, since separate ingresses shouldn't affect each other (unless they're on the same domain).

**Comment by Mo3m3n** [comment]
Hi, 
Your're right about this being a problem making separate ingresses affect each other, it is done this way because changing the path in frontend will impact the routing decision (which is path based). However this was the case before the use of set-var directive to store the path on a variable. So I think we don't have to put paths on backend anymore.  
I will have a closer and get back to you soon with more details or a fix.

**Comment by Mo3m3n** [comment]
This should have been fixed in https://github.com/haproxytech/kubernetes-ingress/commit/10fad906fd7f7da7bc76ba7c4ea17d629e718d05
You can try the tag `haproxytech/kubernetes-ingress:1.4-dev` and let me know if it works as expected.

**Comment by lseelenbinder** [comment]
This is great, @Mo3m3n! Working perfectly, as expected.

If there's no strong reason to avoid running 1.4-dev in production, we'll keep it running until the official 1.4 release since there's no other way to do what we need currently without it.

**Comment by Mo3m3n** [comment]
branch 1.4 is a stable branch (bug fixes and minor changes only), so images built from master (like 1.4-dev tag ) should be also stable and usable on production.  
That being said we will issue a release shortly for 1.4 (this week or next one at latest).

**Comment by Mo3m3n** [comment]
Available on `haproxytech/kubernetes-ingress:1.4.9`
