### ISSUE TITLE
Use an external Haproxy with ingress

### ISSUE THREAD

**Issue by arthurh4** [haproxytech/kubernetes-ingress#240]
Hello,

I would like to know if it is do-able to configure an already existing external HAproxy setup (running outside any k8s cluster) to watch for ingresses resources on k8s clusters and dynamicly generate configs based on that ?

Can it support multi-cluster ingresses ?

I heard it was do-able and I'm trying to find some documentation regarding it but cannot find any.
BTW we are running on GCP/GKE with VPC network which means external VMs can directly communicates with PodIPs and ClusterIps
Thank you

**Comment by prometherion** [comment]
I would say no: right now, Ingress Controller is using the [`client-native`](https://github.com/haproxytech/client-native) that needs to edit-in-place the file configuration. Something could be feasible using the [Dataplane API](https://github.com/haproxytech/dataplaneapi) but it's out of the Kubernetes scope, actually.

What you could do, since you're running in a VPC network, is to run the Ingress Controller consuming a local `kubeconfig` file in order to connect to the Kubernetes API Server, although missing all the advantages of a running Pod (scheduling, affinity, resource limiting, jailing, etc.).

**Comment by oktalz** [comment]
Hi @arthurh4,
running outside k8s cluster to watch for ingresses resources on k8s clusters and dynamically generate configs based on that is possible,  however currently Ingress controller is **only** used like that for testing and debugging purposes.

So you can get haproxy.cfg (in tmp folder) that is the same as it was running in k8s itself.
And if that server where IC is running can reach internal ips of pods this (in theory) could work.

However in this debug/test mode HAProxy reloads and runtime changes are not enabled 
(this was only used to see if the generated config would be ok) and with that its not usable for production. 

This could be expanded further so it does everything like inside of k8 container if this kind of setup is beneficial.

This option is not documented, because currently, its not really a feature that is usable anywhere but for some testing and development

multi-cluster ingresses are currently no tin scope of that
