### ISSUE TITLE
Rate limit by url parameter

### ISSUE THREAD

**Issue by tejohnso** [haproxytech/kubernetes-ingress#244]
According to [this haproxy.com blog post](https://www.haproxy.com/blog/four-examples-of-haproxy-rate-limiting/), we should be able to rate limit by url parameter. However, in the [documentation for the ingress configuration](https://www.haproxy.com/documentation/kubernetes/latest/configuration/ingress/) I don't see how that would be configured. Is it not possible to rate limit by URL parameter when used as an ingress controller?

**Comment by Mo3m3n** [comment]
The `request-rate-limit` annotation currently rate limit by source IP only.
And considering that ingress annotations are applied per Ingress rule (Host + path), the end result is that rate limiting is going to be applied by source IP + host + path.
So this is different from what you want: rate limiting by full URL.  
In order to do that you can resort the `config-snippet` annotation and apply it on the appropriate service.
Example: limit to 1req/5s per host+url
```
config-snippet: |
      stick-table type binary size 1000 store http_req_rate(5s)
      http-request track-sc0 base32+src
      http-request deny if {  base32+src,table_http_req_rate() gt 1 }
```

**Comment by Mo3m3n** [comment]
actually to have the full URL (with params) you wil need to replace `base32+src` by `url32+src`

**Comment by tejohnso** [comment]
Thanks for the assistance.
