### ISSUE TITLE
Ingress with many backends break in 1.4.8+

### ISSUE THREAD

**Issue by Nainterceptor** [haproxytech/kubernetes-ingress#260]
Hello,

First, I've tried to found a right title for this issue, according to my debug, feel free to change it if it's not accurate.

We have an haproxy setup deployed with the following parameters : 
| Name | Value |
|-------|-------|
| controller.service.type | LoadBalancer |
| controller.ingressClass | haproxy |
| controller.replicaCount | null |
| defaultBackend.replicaCount | null |
| controller.extraArgs | {"--ignore-ingress-without-class"} |

And ingress with following annotations :
| Name | Value |
|-------|-------|
| acme.cert-manager.io/http01-edit-in-place | true |
| cert-manager.io/cluster-issuer | letsencrypt-prod |
| kubernetes.io/ingress.class | haproxy |

In version (`controller.image.tag`) 1.4.6 and 1.4.7 (not tested more versions), ingress is rightly edited by cert-manager to add a backend with custom path to resolve challenge HTTP01, and when I call the address, haproxy resolve to the right pod (the cert-manager pod for the specified path)

Since 1.4.8 (included, tested with 1.4.9 and 1.4.10 ; 1.5.0-rc1 trigger another error "the requested IngressClass haproxy doesn't exist", so I guess it's because we will have to upgrade the haproxy chart too with this release), haproxy resolve to the wrong pod (not the cert-manager one, but to the application)

Expected : to resolve to the more specific path when available.

Best regards,

**Comment by Mo3m3n** [comment]
Hi @Nainterceptor 
Thank you first for the detailed information
This was quite useful to quickly spot the problem (and also we may have something to fix for 1.5.0-rc1 regarding IngressClass )
Probably the issue was introduced in this commit 862ed0479359ffa4ceccc4c264283e7a58085e0f where that change introduced a regression by lowering the path matching in backendSwitching.
I have just merged a pending PR https://github.com/haproxytech/kubernetes-ingress/pull/252 fixing this and I have updated nightly build fo stable branch (v1.4) `haproxytech/kubernetes-ingress:1.4-dev`
Can you give it a try and let me know if it solves your problem ?

**Comment by Nainterceptor** [comment]
Hello, 

Just tested, seems to be fixed on 1.4-dev.

**Comment by Mo3m3n** [comment]
Fix available in `1.4.11` thanks again for the detailed report
