### ISSUE TITLE
handle ingress resources without defined class

### ISSUE THREAD

**Issue by dfateyev** [haproxytech/kubernetes-ingress#294]
If haproxy-controller has `ingress.class` defined (e.g. "ingress.class=haproxy") — it refuses to handle ingress resources where an ingress class is not defined (empty).
It's different from other controllers' behavior: the "nginx" controller and alternative "haproxy" controllers both serve ingresses where class is not explicitly defined regardless of their own class.

Could you consider to use the same approach, or introduce a controller option which would allow to do so?
We use a couple of Kubernetes operators where we cannot assign classes, and at the same time we have some ingress resources where we have classes predefined.

Thanks!

**Comment by Mo3m3n** [comment]
The controller used to have that behavior (not ignoring ingress resources with an empty ingress class)
But users asked to change this in https://github.com/haproxytech/kubernetes-ingress/issues/31 and in https://github.com/haproxytech/kubernetes-ingress/issues/165
I guess we will need to introduce a controller option to handle this and satisfy all users.

**Comment by Mo3m3n** [comment]
Handled in https://github.com/haproxytech/kubernetes-ingress/commit/092b80d19a9d5a3b68952b8ad046fb3ee95cbb42 by introducing controller arg [--empty-ingress-class](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--empty-ingress-class) that you can try via `haproxytech/kubernetes-ingress:dev` otherwise it will be in `1.6`

**Comment by dfateyev** [comment]
Checked with 1.6.0, works fine
