### ISSUE TITLE
Permanent Redirect ingress annotation

### ISSUE THREAD

**Issue by AlecTroemel** [haproxytech/kubernetes-ingress#34]
the [community nginx ingresss controller](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect) allows you to set permanent redirects in an ingress's annotations. it would be cool if this controller could do something similar!

**Comment by bedis** [comment]
Hi,
I see. It's technically doable as well with HAProxy.

**Comment by bedis** [comment]
By the way, do you have any use case in mind for this one?

**Comment by donspaulding** [comment]
@bedis Hi, I work with @AlecTroemel.

I believe we use permanent redirects to redirect `http://` to `https://` as well as to redirect `www.domain.name` to the bare `domain.name`.

We also must force the status code to be non-308, because we've had problems with older browsers not redirecting with the 308 code.

**Comment by bedis** [comment]
so schema redirection is already supported, but as a "global" option (for all the traffic processed by the ingress controller). I will create an issue for to support it per ingress or per service.

the domain redirection is not yet possible but this issue will be used to make it possible :)

**Comment by Mo3m3n** [comment]
This is supported via [request-redirect](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#request-redirect) annotation.
