### ISSUE TITLE
Image tag that fixes CVE-2021-40346?

### ISSUE THREAD

**Issue by cdhunt** [haproxytech/kubernetes-ingress#370]
Is there an image that has HAProxy >= 2.3.14?

https://nvd.nist.gov/vuln/detail/CVE-2021-40346

**Comment by Kamaradeivanov** [comment]
If i'm wright, the `haproxytech/kubernetes-ingress` image is based on `haproxytech/haproxy-alpine:2.3` (Ref from the Dockerfile, line 39) in branch v1.6 wich was updated 2 days ago [hub.docker.com](https://hub.docker.com/r/haproxytech/haproxy-alpine/tags?page=1&ordering=last_updated&name=2.3) with the fix for the CVE-2021-40346.

As the image has been build yesterday for the haproxytech/kubernetes-ingress version [1.6.7](https://hub.docker.com/r/haproxytech/kubernetes-ingress/tags?page=1&ordering=last_updated&name=1.6.7) the fix shoud be present, but Iif anyone from @haproxytech could validate my hypoteses it would be nice.

**Comment by oktalz** [comment]
@cdhunt, @Kamaradeivanov  yes, v1.6.7 is updated with latest HAProxy 2.3 version that contains fixes for the mentioned issue.

**Comment by Kamaradeivanov** [comment]
Thanks @oktalz !

According to [artifacthub](https://artifacthub.io/packages/helm/haproxytech/kubernetes-ingress?modal=security-report), there is still hight vulnerabilities that could be fix. Could you confirm that ? And if so have you planned to fix them soon ?

**Comment by oktalz** [comment]
two of them are already fixed on master (just by updating packages) and are in process of reviewing for 1.6 branch
(there is also a nightly build of controller available for testing)

one that is high (regarding ssh) is not relevant to our project since ingress controller is not an ssh server.

but of course, if possible we will update repository to use packages that does not contain any vulnerabilities.
