### ISSUE TITLE
Install fails on GKE autopilot

### ISSUE THREAD

**Issue by akvadrako** [haproxytech/kubernetes-ingress#391]
When I try to follow the instructions for installing the haproxy ingress controller on GKE Autopilot I get the following error:

```
Error from server ([denied by autogke-disallow-privilege] container <sysctl> is privileged; not allowed in Autopilot.
```

**Comment by Mo3m3n** [comment]
The sysctl init container needs to run in privileged mode, is disabling the "autogke-disallow-privilege" constraint a possible option in your case ?

**Comment by akvadrako** [comment]
That isn't possible on Autopilot.

**Comment by Mo3m3n** [comment]
We're using a privileged init container in order to set `sysctl -w net.ipv4.ip_unprivileged_port_start=0` so the Ingress Controller container can be run in unprivileged mode :) 
But we are considering using setcap instead (because setcap should now be widely supported) and get rid of the init container, which will solve this issue.
I am marking this as an enhancement and see if we can have it in IC 1.8

**Comment by dkorunic** [comment]
Patch submitted, review in progress.

**Comment by dkorunic** [comment]
Required IC Dockerfile changes merged in https://github.com/haproxytech/kubernetes-ingress/commit/e0a936e85936806ae47ebfb73ece1fa136453389. New IC 1.8 branch will permit running unprivileged and new Helm Chart will use unprivileged mode by default.
