### ISSUE TITLE
Use Client IP from Proxy Protocol in IP Rate Limiting

### ISSUE THREAD

**Issue by skyward-luke** [haproxytech/kubernetes-ingress#415]
@Mo3m3n 

Background: When deploying kubernetes-ingress to an AWS hosted k8s cluster, a Classic ELB is created with TCP pass-through config, presumably to allow for TLS termination within our k8s cluster via Ingress object config. WIth this frontend AWS TCP proxy, the true client ip is not available to haproxy as an HTTP header, of course. You can enable Proxy Protocol for our new ELB easily, but even with that, the controller does not currently look in the Proxy Protocol to get the client IP for IP-based rate limiting.

Problem: We'd like to use rate-limiting at the proxy level to prevent unwanted traffic from hitting our application pods. We cannot do this currently, given that we use AWS Classic ELB. We could manually update the ELB to use ALB or maybe other manual AWS changes, but preferably the ingress controller would use the Proxy Protocol to fetch the client ip.

**Comment by skyward-luke** [comment]
Any chance this is scheduled for an upcoming release @Mo3m3n ? ( Appreciate all your hard work )

**Comment by skyward-luke** [comment]
Hi @Mo3m3n Thank you for reviewing. It certainly is possible that using another LB type in AWS is a workaround. Because a classic ELB is created by default when installing the controller, we had hoped to use it instead of manually changing the LB type in AWS. I did enable PP for the classic ELB and didn't notice a difference in rate-limiting capabilities of haproxy. Sounds like you suspect this is an issue with ELB, right?

So i think ur proposing to switch from classic ELB to NLB. Do you know, Is it possible to configure the ingress controller to create a NLB on install? Or will it need to be done thru aws cli/ mgmt console?

**Comment by Mo3m3n** [comment]
> I did enable PP for the classic ELB and didn't notice a difference in rate-limiting capabilities of haproxy. Sounds like you suspect this is an issue with ELB, right?

Correct, I think this is an issue with the ELB, I have tried to enable proxy-protocol with ELB and it did not work (no PP headers inserted by the ELB)  so I switched to NLB because the goal is to test that rate-limiting works correctly when PP is enabled, not to debug the ELB.

>  Is it possible to configure the ingress controller to create a NLB on install? Or will it need to be done thru aws cli/ mgmt console?

The Ingress Controller does not create anything (it only configures  haproxy), so I think you can try one of the following:
- troubleshoot the ELB to make it use PP (with AWS support maybe)
- you probably used some tool to create the you aws kubernetes cluster, I guess the same tool is responsible for automatically creating an ELB when required. So you may be able to configure that tool in order to use NLB instead.
- manually migrate your ELB to NLB via cli/mgmt console (at least for the Ingress Controller service to make PP work as expected)

**Comment by skyward-luke** [comment]
Thanks for the clarification - in fact, it appears that switching to NLB is fairly trivial:

![image](https://user-images.githubusercontent.com/67963324/154353715-5e6fdb23-6ed9-4749-8816-3458ac38ce5e.png)

According to the docs, NLB should present the Client IP to pods. Thanks!
