### ISSUE TITLE
Too many metrics caused by default server slots

### ISSUE THREAD

**Issue by Kamaradeivanov** [haproxytech/kubernetes-ingress#427]
Hello, I am using your haproxy solution (v1.6.9) in my company.
But I'm facing some issues with Prometheus metrics on staging environment. 

Actually, I have a little more than 70k entry by pod running, this huge amount of data is caused by 2 aspect : 

- I used the default value (42) of the [scale-server-slots](https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/#scale-server-slots)
- In staging environment I have a lot of temporary ingress rules due to review apps deployment (Gitlab ci)

For each ingress I got 53 metrics. So with 42 server by default, I've got 2226 metrics.
I have actually 32 ingress rules running on staging so I've got 71232 metrics. 

I've deployed my ingress controller with a replica 3 cluster.

So I have two questions : 
- Can I aggregate metrics to have just one by server ?
- Should I have a default value of 42 server slot for a replica 3 cluster ?

**Comment by Mo3m3n** [comment]
Hello
HAProxy prometheus exporter exports by default all metrics available here https://github.com/haproxy/haproxy/tree/master/addons/promex
This may be overkill so that's why it is possible to filter metrics and ask only for process, backend, frontend, etc metrics.
> Can I aggregate metrics to have just one by server ?

This does not make sense because metrics describe different type measures  that cannot be aggregated.
> Should I have a default value of 42 server slot for a replica 3 cluster ?

You can change the number of default server slots available via [scale-server-slots](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#scale-server-slots) annotation.
