### ISSUE TITLE
Problem with CPU/MEMORY usage in controller 1.8.x

### ISSUE THREAD

**Issue by adamw-linadm** [haproxytech/kubernetes-ingress#482]
Hi,
I just updated haproxy kubernetes-ingress  from 1.7.9 to .1.8.3 (helm charts 1.21.1 to 1.22.4) and I started to have a lot of tcp timeouts to my services. My haproxy-ingress deployment started to act very CPU and MEMORY hungry without changing anything in my loadbalancer configuration. I also checked version 1.8.0, this same problem with mem/cpu.
CPU usage graph:
![image](https://user-images.githubusercontent.com/5850150/187519688-bed9f4c6-7e6f-4d3b-9d0e-8af3b617480a.png)
Memory usage graph:
![image](https://user-images.githubusercontent.com/5850150/187520470-c6f7a7ac-3173-4c1c-b14e-d80d898fd7df.png)
Is this problem with controller itself or haproxy (in 1.8.0 haproxy version changed from 1.4 to 1.5).
I also noticed that this change https://github.com/haproxytech/kubernetes-ingress/commit/f1d9cc0255035d7cb3c8528b30c62a2fb6651af9 is buggy:
```
/ # free -m
              total        used        free      shared  buff/cache   available
Mem:          31938        2607       25869         419        3463       28456
Swap:             0           0           0
/ # MEMLIMIT=$(free -m | awk '/Mem:/ {print int($2 * 2 / 3)}')
/ # echo $MEMLIMIT
21292
/ # 
```
So instead of using deployments limits it pass 2/3 od entire node memory to haproxy -m flag

**Comment by dkorunic** [comment]
@adamw-linadm So the calculation is correct when there are no Cgroups v1/v2 limits enabled, but I would agree that it doesn't take into account resource limits when they are enabled. This is being worked on as we speak.

**Comment by adamw-linadm** [comment]
@dkorunic Possible, I use cgroups v2.

**Comment by dkorunic** [comment]
@adamw-linadm Actually no, memory limits are (by default) not enforced and enabling enforcements doesn't really inform HAProxy or Ingress Controller that they are in place and enabled (what's even worse, Cgroups v1 and v2 radically differ in how this information is presented at all) -- nothing in K8s world does this automatically, except OOMK terminating the process which hits the limit. Even more so, this specific change is a workaround for HAProxy `getrlimit()` calculation that is broken under containers specifically due to "broken" way K8s/Docker containers handle resource limits.

**Comment by dkorunic** [comment]
Fixed in https://github.com/haproxytech/kubernetes-ingress/commit/3dbd1eb629d945dbda38241449ca2c36d52c03dd, we now have support for both Cgroups v1  and Cgroups v2 where applicable. Also when resource limits have not been enforced, we will failover to using node memory limits, since in case of limits not being enabled, resource limits have invalid/unusable counters. This improvement will be backported to stable branch as well.

**Comment by adamw-linadm** [comment]
Thanks @dkorunic I will check it after release.

**Comment by dkorunic** [comment]
Helm Chart `v1.23.1` uses IC `v1.8.5` release and should contain relevant Cgroup/memory fixes. Please test when/if you can.

**Comment by adamw-linadm** [comment]
@dkorunic everything works perfect now, thank You :)

**Comment by dkorunic** [comment]
Glad to hear that @adamw-linadm, thanks for confirming!
