### ISSUE TITLE
Client IP with src-ip-header not preserved with default backend service

### ISSUE THREAD

**Issue by evandam** [haproxytech/kubernetes-ingress#492]
Hi folks, we're seeing HAProxy access logs that vary depending on whether or not a request makes it to an upstream service or is sent to the default backend.

If a request makes it to a backend successfully, the client IP seems to be preserved correctly (note the `src-ip-header` in the configmap). However, if a request goes to the default backend with a 404 status, the client IP is not preserved, and is instead the IP of one of our ALBs in front of our HAProxy ingress.

For example, assuming you have a Podinfo service for podinfo.example.com:

```bash
# NOTE: Request to a valid service
curl https://podinfo.example.com/
# NOTE: Valid HAProxy logs. First field is the correct client IP
73.189.169.42:27496 10.55.4.23:9898 [12/Oct/2022:16:21:35.648] http cloudops_podinfo_http/SRV_1 0/0/0/0/0 404 175 - - ---- 3/3/0/0/0 0/0 {curl/7.79.1} "GET podinfo.example.com/ HTTP/1.1" - 35bb66bb-e2cb-4e4b-9bb9-b707127361be

# NOTE: Change the Host header so HAProxy doesn't have a matching route
curl https://podinfo.example.com/invalid-route -H 'Host: bad.example.com'
# NOTE: The client IP in the first field is now an IP from our AWS ALB
10.55.206.13:7202 10.55.0.220:8080 [12/Oct/2022:16:23:12.403] http haproxy_haproxy-kubernetes-ingress-default-backend_http/SRV_2 0/0/0/0/0 404 148 - - ---- 1/1/0/0/0 0/0 {} "GET bad.example.com/invalid-route HTTP/1.1" - e1862a28-2f7d-4c7f-ab2c-433d04dc1598
```

We're deploying HAProxy ingress with Helm chart 1.23.1 and the following configmap (trimming out irrelevant bits):

```yaml
controller:
        service:
          type: NodePort
        config:
          # NOTE: Set the client IP to the forwarded by the ALB
          src-ip-header: X-Forwarded-For
          # NOTE: Don't set the X-Forwarded-For header since it is already set to the client
          forwarded-for: "false"
          frontend-config-snippet: |
            unique-id-format %[uuid()]
            unique-id-header X-Request-Id
          request-capture: |
            hdr(User-Agent)
          # NOTE: See: https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/#log-format
          # NOTE: Include backend server ip:port and request ID
          log-format: "%ci:%cp %si:%sp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs \"%HM %[var(txn.base)] %HV\" - %ID"
        logging:
          level: info
          traffic:
            address: stdout
            format: raw
            facility: daemon
      # NOTE: The default backend is used for HAProxy's service health checks
      defaultBackend:
        enabled: true
```

Please let me know if there are any other details I can provide. I think the fields to note would really just be `controller.config.src-ip-header`, `controller.config.forwarded-for` (our ALB already sets the X-Forwarded-For header, so there's no need for HAProxy to modify it again), and `controller.config.log-format`.

Thanks in advance 🙌

**Comment by scalp42** [comment]
Can confirm, the behavior is only seen on `default-backend` (the logs always report the ALB in front of it vs client IP) 👀

**Comment by ivanmatmati** [comment]
Thanks @evandam and @scalp42 for your report. @evandam can you show the frontend configuration from haproxy file as well as a service backend and default backend 's ones?

**Comment by evandam** [comment]
Hey @ivanmatmati sure thing, giving any config here that might be helpful too: https://gist.github.com/evandam/2912bb1caf9e08b2b26486ff7d920325

**Comment by fabianonunes** [comment]
Hi, @ivanmatmati.

I think this regression was caused by commit f04679a7, which started processing all ConfigMap annotations when handling Ingress Annotations to fix the precedence between them. See line 148:

https://github.com/haproxytech/kubernetes-ingress/blob/f04679a7415a7cfa564b4cf3b43ea6189ed4a317/pkg/ingress/ingress.go#L144-L154

Ingress annotations are handled after the ConfigMap ones and will override them, linking the rules to a path_match. Since the default backend does not match any path, no ConfigMap annotations will be applied to it. See the resulting rule of the `src-ip-header` annotation:

```text
http-request set-src hdr(X-Forwarded-For) if { var(txn.path_match) -m dom 30971f726a7be9f3280fd9be67b0d85f }
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Although I have defined the annotation in ConfigMap, it is bound to a path_match and isn't applied to the default backend.

@evandam, as a workaround, you can use [`frontend-config-snippet`](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md#config-snippet) to apply the rule without path matching:

```yaml
frontend-config-snippet: |
  http-request set-src hdr(X-Forwarded-For)
```

**Comment by ivanmatmati** [comment]
Hi @fabianonunes , Actually the code extract is correct because you still need to apply ingress configuration with higher precedence order than configmap. Otherwise you can't redefine global values specifically for an ingress. This also implies that a rule is always mapped to an id so that you can map a more specific rule to an ingress or even disable it. Anyway, I've already spotted the cause and implemented the issue.

**Comment by fabianonunes** [comment]
Ah, now I get it. Sorry, isn't a regression, it's a consequence.

**Comment by ivanmatmati** [comment]
You're welcome. Thanks for your support to others.

**Comment by evandam** [comment]
Thanks for digging into this @fabianonunes!

I think I understand what's going on, but it definitely shouldn't be expected behavior if we agree? Or if it is, then the docs should be updated with a disclaimer that ConfigMap entries like [src-ip-header](https://www.haproxy.com/documentation/kubernetes/latest/configuration/configmap/#src-ip-header) may be completely ignored depending on the backend the request is going to?

**Comment by ivanmatmati** [comment]
Hi @evandam , We've discussed that internally and the possibility to get the ip address for 404 miss is definitely helpful. So I've added a clause to the rule for src-ip-header. It is available in nigthly build as docker image. Can you test that ?

**Comment by scalp42** [comment]
@kuhar2007 can you set `forwarded-for` to `"false"` and try again for science 🙏

**Comment by kuhar2007** [comment]
> @kuhar2007 can you set `forwarded-for` to `"false"` and try again for science 🙏

Didn't help me:
`10.233.114.0:50912 10.233.104.179:80 [06/Dec/2023:10:49:52.107] http haproxy-controller_test-page_tcp-web/SRV_1 0/0/1/3/4 200 197 - - ---- 1/1/0/0/0 0/0 {} "HEAD test-page.example.com/ HTTP/1.1" - 58e482a3-ad4c-4ffe-b010-8d8f981c3846`
