### ISSUE TITLE
Are there any releases built with the USE_ZLIB=1 option set?

### ISSUE THREAD

**Issue by jcurtis789** [haproxytech/kubernetes-ingress#538]
I'm looking for an HA Proxy Ingress controller that is capable of gzip compression. I've pulled a number of haproxytech/kuberenetes-ingress tags myself (1.5.6, 1.6.5, 1.7.0, 1.8.0, 1.9.0, 1.10.0) and none of them have the option set.

1.10.0:
OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_PROMEX=1
Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Are there any options available to me in the current project? If not, is the recommendation that I build HAProxy myself and supply it to the image? I think I found where HA Proxy for kubernetes-ingress is built:
https://github.com/haproxytech/haproxy-docker-alpine/blob/main/2.8/Dockerfile#L45

Thanks!

**Comment by jcurtis789** [comment]
I'm closing this issue. USE_SLZ accomplishes the same thing, I'm just behind the times.

**Comment by dkorunic** [comment]
Dear @jcurtis789 , there is no need to do rebuild HAProxy with `USE_ZLIB`, since that option would activate standard system Zlib support instead of high-throughput [SLZ](http://1wt.eu/projects/) which is active by default through `USE_SLZ=1`. SLZ creates stream output fully compatible with browsers' gzip stream support and uses much less memory and much less CPU compared to standard Zlib.
