### ISSUE TITLE
Runtime API changes not getting synced between haproxy replicas

### ISSUE THREAD

**Issue by fo511** [haproxytech/kubernetes-ingress#665]
Hello there.
Ocasionally I find out that havig multple pods of ingress is heading to some configuration drift between them. For example I want to cordon some service/pod. So I set status for them to drain/maint/etc via stats page or runtime api.
At this time, another haproxy instances do not sync these changes. So end user still can go to cordoned pod/service via another haproxy instance with no problem. One way that i found - is to run haproxy ingress without any replicas.
Not sure if this behaviour is bug or it's working as intended.

**Comment by oktalz** [comment]
hi @fo511 
this is not really possible currently. changing status on one ingress controller is not planned to be synced with other controllers. 
In fact IC is not expecting user doing changes manually at all. Its fully dependent on state that k8s provides.

in order to put some server in maint/..., yes you need to loop through all instances and do it one by one

hence for example we have comments in config file:
```
# this file is not meant to be changed directly
# it is under haproxy ingress controller management
```
it still works is you do it manually, but is sort of out of scope of IC

>Not sure if this behavior is bug or it's working as intended.

it is working as intended, each instance is working independently. We do have different products that do it in a way that you need, however IC is not syncing states.

**Comment by fo511** [comment]
@oktalz so it means that functions like peering for stick-tables won't work correctly? Cause it supposed to work with active-passive nodes schema while IC is active-active. isn't it?
