### ISSUE TITLE
Add middleware feature

### ISSUE THREAD

**Issue by mike-code** [haproxytech/kubernetes-ingress#680]
`Ingress` resource supports `backend-config-snippet` annotation, however there is no convenient way to share the same logic (ie. snippet) across many `Ingress` resources.

The idea is to have a kind of "middleware" where you define `backend-snippet` in global `ConfigMap` and then load it via `haproxy.org/middleware: run_me`.

Note: the controller would have to watch configmap for changes and update all `Ingress`'es should the `run_me` function/logic change.

**Comment by oktalz** [comment]
hi @mike-code,

for that purpose you can use backend [CRD](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/custom-resources.md) 
we do not plan to add more options for snippets, since you can do the same with CRDs, and custom resources are better in basically every way (scheme, validation ...)
